name: Markdown Lint and Spell Check

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
        pip install codespell

    - name: Run Markdown lint
      run: markdownlint '**/*.md'

    - name: Run spell check
      run: codespell --ignore-words-list="ci,cpu,repo" .
